### POST - Create new role.
POST http://localhost:8080/role HTTP/1.1
Content-Type: application/json

{
  "name":"Role Test",
  "description":"Role Test Description."
}

### PUT - Update role that exists.
PUT http://localhost:8080/role HTTP/1.1
Content-Type: application/json

{
  "name":"Role Test",
  "description":"Role Test A Description."
}

### DELETE - Delete role that exists.
DELETE http://localhost:8080/role HTTP/1.1
Content-Type: application/json

{
"name":"Role Test",
"description":"Role Test A Description."
}

### GET - Get All Roles.
GET http://localhost:8080/role?page=0&limit=5&sort=asc HTTP/1.1
Content-Type: application/json

### GET - Get Role By Name.
GET http://localhost:8080/role/findByName?name=Role Test HTTP/1.1
Content-Type: application/json